---

language: python
python: "2.7"

sudo: required

services:
  - docker
  
before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -qq python-apt

install:
  - pip install ansible==1.9.1

script:
# Building Docker image to run mypaas playbook
- docker build -t "mypaas" .
# Role syntax
- docker run -i mypaas ansible-playbook -i "localhost," -c local main.yml --syntax-check
